# -*- coding: utf-8 -*-
"""Corelations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PHxrICtRyCtBLgu1T4j9C-W4i-MUMsqe
"""

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42) # makes results the same every time you run
n = 50 # we will use 50 data points
x = np.linspace(1, 10, n) # x values from 1 to 10

# Positive: y goes UP as x goes up
y_pos = 5 * x + np.random.normal(0, 2, n)

# Negative: y goes DOWN as x goes up
y_neg = -2 * x + 25 + np.random.normal(0, 2, n)

# No correlation: y is random, not related to x at all
y_none = np.random.normal(10, 3, n)

# Draw three plots side by side
fig, axes = plt.subplots(1, 3, figsize=(14, 4))

axes[0].scatter(x, y_pos, color='steelblue', alpha=0.7)
axes[0].set_title('Positive Correlation')

axes[1].scatter(x, y_neg, color='coral', alpha=0.7)
axes[1].set_title('Negative Correlation')

axes[2].scatter(x, y_none, color='seagreen', alpha=0.7)
axes[2].set_title('No Correlation')

for ax in axes:
    ax.set_xlabel('X'); ax.set_ylabel('Y')
    ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
stdhrs = np.array([1,2,3,4,5,6,7])
scores = np.array([40,45,57,63,72,85,93])

plt.scatter(stdhrs, scores)
plt.title('Hours of Study vs. Test Scores')
plt.xlabel('Hours of Study')
plt.ylabel('Test Score')
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
# Our student dataset
study_hours = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
exam_scores = [88, 80,75,70,62,55,50,44,38,30]
# --- Calculate Pearson r ---
r, p = stats.pearsonr(study_hours, exam_scores)
print(f'Pearson r = {r:.3f}')
print(f'P-value = {p:.4f}')
if p < 0.05:
 print('This correlation is statistically significant.')
else:
 print('This correlation may be due to chance.')
# --- Scatter plot with trend line ---
plt.figure(figsize=(7, 5))
plt.scatter(study_hours, exam_scores, color='steelblue', s=100, zorder=5)
# Calculate and draw trend line
m, b = np.polyfit(study_hours, exam_scores, 1) # m = slope, b = intercept
x_line = np.linspace(min(study_hours), max(study_hours), 100)
plt.plot(x_line, m * x_line + b, 'r--', linewidth=2,
 label=f'Trend line (r = {r:.3f})')
plt.xlabel('Study Hours per Day')
plt.ylabel('Exam Score')
plt.title('Study Hours vs Exam Score')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
# Our student dataset
study_hours = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
exam_scores = [88, 80,75,70,20,55,50,44,38,30]
# --- Calculate Pearson r ---
r, p = stats.pearsonr(study_hours, exam_scores)
print(f'Pearson r = {r:.3f}')
print(f'P-value = {p:.4f}')
if p < 0.05:
 print('This correlation is statistically significant.')
else:
 print('This correlation may be due to chance.')
# --- Scatter plot with trend line ---
plt.figure(figsize=(7, 5))
plt.scatter(study_hours, exam_scores, color='steelblue', s=100, zorder=5)
# Calculate and draw trend line
m, b = np.polyfit(study_hours, exam_scores, 1) # m = slope, b = intercept
x_line = np.linspace(min(study_hours), max(study_hours), 100)
plt.plot(x_line, m * x_line + b, 'r--', linewidth=2,
 label=f'Trend line (r = {r:.3f})')
plt.xlabel('Study Hours per Day')
plt.ylabel('Exam Score')
plt.title('Study Hours vs Exam Score')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
# Our student dataset
study_hours = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
exam_scores = [42, 50, 58, 63, 70, 74, 80, 85, 90, 95]
absentdays = [0,1,1,2,3,3,4,5,6,7]


# --- Calculate Pearson r ---
r, p = stats.pearsonr(absentdays, exam_scores)
print(f'Pearson r = {r:.3f}')
print(f'P-value = {p:.4f}')
if p < 0.05:
 print('This correlation is statistically significant.')
else:
 print('This correlation may be due to chance.')
# --- Scatter plot with trend line ---
plt.figure(figsize=(7, 5))
plt.scatter(absentdays, exam_scores, color='steelblue', s=100, zorder=5)
# Calculate and draw trend line
m, b = np.polyfit(absentdays, exam_scores, 1) # m = slope, b = intercept
x_line = np.linspace(min(absentdays), max(absentdays), 100)
plt.plot(x_line, m * x_line + b, 'r--', linewidth=2,
 label=f'Trend line (r = {r:.3f})')
plt.xlabel('Absence Day')
plt.ylabel('Exam Score')
plt.title('Absence vs Exam Score')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()