# -*- coding: utf-8 -*-
"""Data_plotting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SMZaYeQ8eOls321pF-xcbRCXZEcHDroZ
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df = sns.load_dataset('titanic')

df.head()

df = sns.load_dataset('tips')
df

sns.histplot(data=df,x='tip')
plt.show()

sns.kdeplot(data=df,x='tip')
plt.show()

sns.scatterplot(data=df,x=df['total_bill'], y='tip')
plt.show()

sns.lineplot(data=df,x=df['total_bill'], y='tip')
plt.show()

sns.regplot(data=df,x=df['total_bill'], y='tip')
plt.show()

sns.barplot(data=df,x='day', y='total_bill')
plt.show()

sns.countplot(data=df,x='day')
plt.show()

sns.boxplot(data=df,x='day', y='tip')
plt.show()

sns.violinplot(data=df,x='day', y='tip')
plt.show()

sns.stripplot(data=df,x='day', y='tip')
plt.show()

sns.swarmplot(data=df,x='day', y='tip')
plt.show()

sns.pairplot(df)
plt.show()

sns.set_style('whitegrid')
sns.pairplot(data=df,hue='sex', palette='Set2', diag_kind='kde')
plt.show()

df = pd.read_csv('USA_Housing.csv')
df

df.describe()

df.index

sns.pairplot(df)
plt.show()