# -*- coding: utf-8 -*-
"""Tabular_Data_Manipulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16YuGzENJQKopi0oVHYcN9NTamOLhXWYJ
"""

import pandas as pd

df = pd.read_csv("/content/titanic.csv")

df.head(3)

df.tail()

df.shape

df.info()

df.describe()

df.head()

"""# handlilng Categorical features"""

df =df.drop('Name', axis = 1)

df

df = df.drop('Ticket', axis = 1)
df = df.drop('Cabin', axis = 1)

df

df['Sex'].nunique()

df['Sex'].unique()

df['Embarked'].unique()

df['Embarked'] = df['Embarked'].map({'S':0, 'C':1, 'Q':2})

df.head()

df['Embarked'].unique()

df['Sex'] =df['Sex'].map({'male':0, 'female':1})

df.head()

"""# hadling null values"""

df.info()

df['Embarked'].isnull().sum()

df['Embarked'] = df['Embarked'].fillna(0)

df.info()

df.describe()

df['Age'] = df['Age'].fillna(29)

df.info()

df.duplicated().sum()

import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(x = df['Fare'])
plt.show()

"""# NOrmalization and standardization"""

from sklearn.preprocessing import MinMaxScaler, StandardScaler

NN = MinMaxScaler()
SD = StandardScaler()

df['Age'] = NN.fit_transform(df[['Age']])
df['Fare'] = SD.fit_transform(df[['Fare']])

df.head()