# -*- coding: utf-8 -*-
"""CLASSIFICATION WITH KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IGgbOptoaucoNlrUGS8rFd2st52RqCSt

# KNN (K-NEAREST NEIGHBOURS): A CLASSIFICATION ALGORITHM
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""### 1. Load data & drop missing values"""

df = sns.load_dataset('penguins')
df

df = df.dropna()
df

"""## 2. Feature selection"""

df.columns

df['species'].value_counts()

X = df[['bill_length_mm','bill_depth_mm','flipper_length_mm', 'body_mass_g']]
y = df['species']

X

y

"""## 3. Split X & y into training and testing"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=40)

"""## 4. Feature Scaling"""

from sklearn.preprocessing import StandardScaler
# mean = 0, std = 1
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled

X_test_scaled

"""## 5. Train KNN"""

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5)

knn.fit(X_train_scaled,y_train)

"""## 6. Prediction"""

y_pred = knn.predict(X_test_scaled)
y_pred

y_test

"""## 7. Evaluation"""

print('Predicted Species: ', y_pred[0])
print('Actual Species: ', y_test.iloc[0])

print('Predicted Species: ', y_pred[-1])
print('Actual Species: ', y_test.iloc[-1])

from sklearn.metrics import accuracy_score
print('Accuracy Score: ',accuracy_score(y_test,y_pred) * 100)

"""### Confusion Matrix"""

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()
# 1. Feature Selection
X = pd.DataFrame(data.data, columns = data.feature_names)
y = data.target     # 0 = malignant, 1 = benign

# 2. Split X & y into training & test
# 3. Scale the X features
# 4. Train knn on k = 5
# 5. Predict on X_test and save predictions in y_pred
# 6. Evaluate (Compare y_test & y_pred)
# 7. Print model accuracy & Confusion matrix, classification

# 2. Split X & y into training & test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=40)

# 3. Scale the X features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 4. Train knn on k = 5
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(X_train_scaled,y_train)

# 5. Predict on X_test and save predictions in y_pred
y_pred = knn.predict(X_test_scaled)
y_pred
y_test

# 6. Evaluate (Compare y_test & y_pred)
print('Predicted : ', y_pred[0])
print('Actual : ', y_test[0])

# 7. Print model accuracy & Confusion matrix, classification
from sklearn.metrics import accuracy_score
print('Accuracy Score: ',accuracy_score(y_test,y_pred) * 100)
print("_________________________")
# confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)
#classification
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))