# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13IKFaHJ0H1z7haBXaQtvm2MAzSvbz8Ls
"""

import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, root_mean_squared_error, mean_squared_error, r2_score, mean_absolute_error
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor

df = sns.load_dataset('diamonds')
df

df.columns

x = df[['carat', 'depth', 'table', 'x', 'y', 'z']]
y = df[['price']]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

s = StandardScaler()
x_train = s.fit_transform(x_train)
x_test = s.transform(x_test)

model = KNeighborsRegressor(n_neighbors=5)
model.fit(x_train, y_train.values.ravel())
y_pred = model.predict(x_test)
y_pred

plt.scatter(y_test, y_pred)
plt.plot(y_test, y_test, color='red')
plt.xlabel('y_test')
plt.ylabel('y_pred')
plt.show()