# -*- coding: utf-8 -*-
"""LinearReg_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rmF6f5u7579SLV2JqwSOe6-UBctfN-nY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
np.random.seed(42)
n = 100

# Generate student data
study = np.random.normal(6, 2, n).clip(0, 12) # hours studying
sleep = np.random.normal(7, 1.5, n).clip(4, 10) # hours sleeping
attend = np.random.normal(80, 15, n).clip(40, 100) # attendance %
gpa = np.random.normal(3.0, 0.5, n).clip(1, 4) # previous GPA

# Exam score depends on all four features
score = (8*study + 3*sleep + 0.2*attend + 12*gpa +
 np.random.normal(0, 5, n)).clip(0, 100)


df = pd.DataFrame({
 'study': study,
 'sleep': sleep,
 'attend': attend,
 'gpa': gpa,
 'score': score
})
y = df['score']

# --- Model A: only study hours (like Lab 3) ---
X_A = df[['study']]
X_tr_A, X_te_A, y_tr, y_te = train_test_split(X_A, y, test_size=0.2,
random_state=42)
model_A = LinearRegression()
model_A.fit(X_tr_A, y_tr)
r2_A = r2_score(y_te, model_A.predict(X_te_A))
print(f'Model A (study only): R² = {r2_A:.3f}')

# --- Model B: all four features ---
X_B = df[['study', 'sleep', 'attend', 'gpa']]
X_tr_B, X_te_B, _, _ = train_test_split(X_B, y, test_size=0.2, random_state=42)
model_B = LinearRegression()
model_B.fit(X_tr_B, y_tr)
r2_B = r2_score(y_te, model_B.predict(X_te_B))
print(f'Model B (all 4 features): R² = {r2_B:.3f}')
print(f'Improvement: +{(r2_B - r2_A)*100:.1f} percentage points')

# --- Which features matter most? ---
features = ['study', 'sleep', 'attend', 'gpa']
weights = model_B.coef_
print('Feature weights (larger = more influence):')
for name, w in zip(features, weights):
 print(f' {name:8s} {w:+.3f}')
# --- Visualise: R² comparison ---
plt.figure(figsize=(7, 4))
bars = plt.bar(['Model A\n(1 feature)', 'Model B\n(4 features)'],
 [r2_A, r2_B], color=['steelblue', 'coral'], edgecolor='black', width=0.4)
# Add labels on top of bars
for bar, val in zip(bars, [r2_A, r2_B]):
 plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01, f'R² = {val:.3f}', ha='center', fontweight='bold')
plt.ylim(0, 1)
plt.ylabel('R² Score')
plt.title('More Features → Better Predictions')
plt.grid(True, alpha=0.3, axis='y')
plt.show()
# --- Predict for a new student ---
new_student = pd.DataFrame({
 'study': [2],
 'sleep': [8],
 'attend': [85],
 'gpa': [3.2]
})
pred = model_B.predict(new_student)[0]
print(f'Predicted score for new student: {pred:.1f}')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
np.random.seed(42)
n = 100

# Generate student data
study = np.random.normal(6, 2, n).clip(0, 12) # hours studying
gpa = np.random.normal(3.0, 0.5, n).clip(1, 4) # previous GPA

# Exam score depends on all four features
score = (8*study  + 12*gpa +
 np.random.normal(0, 5, n)).clip(0, 100)


df = pd.DataFrame({
 'study': study,
 'gpa': gpa,
 'score': score
})
y = df['score']

# --- Model A: only study hours (like Lab 3) ---
X_A = df[['study']]
X_tr_A, X_te_A, y_tr, y_te = train_test_split(X_A, y, test_size=0.2,
random_state=42)
model_A = LinearRegression()
model_A.fit(X_tr_A, y_tr)
r2_A = r2_score(y_te, model_A.predict(X_te_A))
print(f'Model A (study only): R² = {r2_A:.3f}')

# --- Model B: all four features ---
X_B = df[['study', 'gpa']]
X_tr_B, X_te_B, _, _ = train_test_split(X_B, y, test_size=0.2, random_state=42)
model_B = LinearRegression()
model_B.fit(X_tr_B, y_tr)
r2_B = r2_score(y_te, model_B.predict(X_te_B))
print(f'Model B (all 2 features): R² = {r2_B:.3f}')
print(f'Improvement: +{(r2_B - r2_A)*100:.1f} percentage points')

# --- Which features matter most? ---
features = ['study', 'gpa']
weights = model_B.coef_
print('Feature weights (larger = more influence):')
for name, w in zip(features, weights):
 print(f' {name:8s} {w:+.3f}')
# --- Visualise: R² comparison ---
plt.figure(figsize=(7, 4))
bars = plt.bar(['Model A\n(1 feature)', 'Model B\n(2 features)'],
 [r2_A, r2_B], color=['steelblue', 'coral'], edgecolor='black', width=0.4)
# Add labels on top of bars
for bar, val in zip(bars, [r2_A, r2_B]):
 plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01, f'R² = {val:.3f}', ha='center', fontweight='bold')
plt.ylim(0, 1)
plt.ylabel('R² Score')
plt.title('More Features → Better Predictions')
plt.grid(True, alpha=0.3, axis='y')
plt.show()
# --- Predict for a new student ---
new_student = pd.DataFrame({
 'study': [7],
 'gpa': [3.2]
})
pred = model_B.predict(new_student)[0]
print(f'Predicted score for new student: {pred:.1f}')