# -*- coding: utf-8 -*-
"""Linear Regression with Pytorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MzcOjWHGwneSh19vilQK8vtozuInyKmg
"""

import numpy as np

# Features (2 features)
X = np.array([
    [2, 7],
    [3, 6],
    [4, 6],
    [5, 5],
    [6, 5],
    [7, 4]
])

# Target
y = np.array([50, 55, 65, 70, 75, 78])

y.shape

import torch

X_t = torch.tensor(X, dtype=torch.float32)
y_t = torch.tensor(y, dtype=torch.float32).view(-1, 1)

y_t.shape

model = torch.nn.Linear(2,1)

criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

epochs = 1000

for epoch in range(epochs):

    y_pred = model(X_t)

    print(y_pred.shape)

    loss = criterion(y_pred, y_t)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.2f}")

x_test = torch.tensor([[8, 4]], dtype=torch.float32)

prediction = model(x_test)
print("Predicted Score:", prediction.item())