# -*- coding: utf-8 -*-
"""Linear_Regression_From_Scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MhiI36Frs31Mg2xGjtRFQoCPwfawwl_F
"""

import numpy as np

# Features (2 features)
X = np.array([
    [2, 7],
    [3, 6],
    [4, 6],
    [5, 5],
    [6, 5],
    [7, 4]
])

# Target
y = np.array([50, 55, 65, 70, 75, 78])

y.shape

# Initialize weights
w = np.zeros(2)
b = 0.0

# Initialize the hyper parameters
lr = 0.01
Epochs = 1000

# total samples and loss list
n = len(X)

losses = []

w.shape

X.shape

ans = np.dot(X, w)
ans

# Training loop

for e in range(Epochs):

  # Forward pass
  y_p = np.dot(X, w) + b
  print(y_p.shape)

  # loss
  loss = np.mean((y - y_p)**2)

  losses.append(loss)

  # Gradients
  dw = (-2/n)* np.dot(X.T, (y - y_p))
  db = (-2/n) * np.sum(y - y_p)

  # Update the weights
  w_new = w - (lr*dw)
  b_new = b - (lr*db)

  # Update the weights
  w = w_new
  b = b_new

w, b

import matplotlib.pyplot as plt

plt.plot(losses)
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Training Loss Curve")
plt.show()

# testing

X_test = np.array([
    [8, 4],
    [3, 7],
    [6, 2]
])

y_pred_test = np.dot(X_test, w) + b

print("Predictions:", y_pred_test)